name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container: circleci/golang:1.15
    steps:
      # This Docker file changes sets USER to circleci instead of using the default user, so we need to update file permissions for this image to work on GH Actions.
      # See https://docs.github.com/actions/reference/virtual-environments-for-github-hosted-runners#docker-container-filesystem
      - name: Setup file system permissions
        run: sudo chmod -R 777 $GITHUB_WORKSPACE /github /__w/_temp
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: make deps
      - name: Lint
        run: make lint
      - name: Vet
        run: make vet
      - name: Test
        run: make test

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Set version env
        run: echo "CUSTOM_VERSION=$(cat VERSION).$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
      - name: Print version
        run: echo $CUSTOM_VERSION
      - name: Print version again
        run: echo ${{ env.CUSTOM_VERSION }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker build
        run: make docker_build
        id: docker_build
      - name: Log in to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          name: ollieparsley/social-media-user-exporter
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ollieparsley/social-media-user-exporter:${{ env.CUSTOM_VERSION }}
            ollieparsley/social-media-user-exporter:latest
      - name: Docker Hub Description
        if: github.ref == 'refs/heads/main'
        uses: peter-evans/dockerhub-description@v2
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          DOCKERHUB_REPOSITORY: peterevans/dockerhub-description

